services:
  - type: web
    name: member-service-api
    runtime: docker
    plan: free
    autoDeploy: true
    branch: main
    buildCommand: dotnet build
    startCommand: dotnet MemberService.Api.dll
    rootDir: MemberService.Api
